/// LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const GET_USER = 'GET_USER'
export const LOG_OUT = 'LOG_OUT'

/// ALERTS

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'


// Listado

 export const CREATE_LISTADO = "CREATE_LISTADO"
 export const CREATE_LISTADO_SUCCESS = "CREATE_LISTADO_SUCCESS"
 export const CREATE_LISTADO_ERROR = "CREATE_LISTADO_ERROR"
 export const VIEW_LISTADO = "VIEW_LISTADO"
 export const VIEW_LISTADO_SUCCESS = "VIEW_LISTADO_SUCCESS"
 export const VIEW_LISTADO_ERROR = "VIEW_LISTADO_ERROR"
 export const EDIT_LISTADO = "EDIT_LISTADO"
 export const EDIT_LISTADO_SUCCESS = "EDIT_LISTADO_SUCCESS"
 export const EDIT_LISTADO_ERROR = "EDIT_LISTADO_ERROR"
 export const UPDATE_LISTADO = "UPDATE_LISTADO"
 export const UPDATE_LISTADO_SUCCESS = "UPDATE_LISTADO_SUCCESS"
 export const UPDATE_LISTADO_ERROR = "UPDATE_LISTADO_ERROR"
 export const DELETE_LISTADO = "DELETE_LISTADO"
 export const DELETE_LISTADO_SUCCESS = "DELETE_LISTADO_SUCCESS"
 export const DELETE_LISTADO_ERROR = "DELETE_LISTADO_ERROR"
 export const CLEAN_LISTADO = "CLEAN_LISTADO"


 export const CREATE_ZONA = "CREATE_ZONA"
 export const CREATE_ZONA_SUCCESS = "CREATE_ZONA_SUCCESS"
 export const CREATE_ZONA_ERROR = "CREATE_ZONA_ERROR"
 export const VIEW_ZONA = "VIEW_ZONA"
 export const VIEW_ZONA_SUCCESS = "VIEW_ZONA_SUCCESS"
 export const VIEW_ZONA_ERROR = "VIEW_ZONA_ERROR"
 export const EDIT_ZONA = "EDIT_ZONA"
 export const EDIT_ZONA_SUCCESS = "EDIT_ZONA_SUCCESS"
 export const EDIT_ZONA_ERROR = "EDIT_ZONA_ERROR"
 export const UPDATE_ZONA = "UPDATE_ZONA"
 export const UPDATE_ZONA_SUCCESS = "UPDATE_ZONA_SUCCESS"
 export const UPDATE_ZONA_ERROR = "UPDATE_ZONA_ERROR"
 export const DELETE_ZONA = "DELETE_ZONA"
 export const DELETE_ZONA_SUCCESS = "DELETE_ZONA_SUCCESS"
 export const DELETE_ZONA_ERROR = "DELETE_ZONA_ERROR"
 export const CLEAN_ZONA = "CLEAN_ZONA"

 export const CREATE_USUARIO = "CREATE_USUARIO"
 export const CREATE_USUARIO_SUCCESS = "CREATE_USUARIO_SUCCESS"
 export const CREATE_USUARIO_ERROR = "CREATE_USUARIO_ERROR"
 export const VIEW_USUARIO = "VIEW_USUARIO"
 export const VIEW_USUARIO_SUCCESS = "VIEW_USUARIO_SUCCESS"
 export const VIEW_USUARIO_ERROR = "VIEW_USUARIO_ERROR"
 export const EDIT_USUARIO = "EDIT_USUARIO"
 export const EDIT_USUARIO_SUCCESS = "EDIT_USUARIO_SUCCESS"
 export const EDIT_USUARIO_ERROR = "EDIT_USUARIO_ERROR"
 export const UPDATE_USUARIO = "UPDATE_USUARIO"
 export const UPDATE_USUARIO_SUCCESS = "UPDATE_USUARIO_SUCCESS"
 export const UPDATE_USUARIO_ERROR = "UPDATE_USUARIO_ERROR"
 export const DELETE_USUARIO = "DELETE_USUARIO"
 export const DELETE_USUARIO_SUCCESS = "DELETE_USUARIO_SUCCESS"
 export const DELETE_USUARIO_ERROR = "DELETE_USUARIO_ERROR"
 export const CLEAN_USUARIO = "CLEAN_USUARIO"
 
 
 export const REDIRECT = "REDIRECT"

 export const VIEW_RESIDENCIA = "VIEW_RESIDENCIA"
 export const VIEW_RESIDENCIA_SUCCESS = "VIEW_RESIDENCIA_SUCCESS"
 export const VIEW_RESIDENCIA_ERROR = "VIEW_RESIDENCIA_ERROR"
 export const EDIT_RESIDENCIA = "EDIT_RESIDENCIA"
 export const EDIT_RESIDENCIA_SUCCESS = "EDIT_RESIDENCIA_SUCCESS"
 export const EDIT_RESIDENCIA_ERROR = "EDIT_RESIDENCIA_ERROR"
 export const UPDATE_RESIDENCIA = "UPDATE_RESIDENCIA"
 export const UPDATE_RESIDENCIA_SUCCESS = "UPDATE_RESIDENCIA_SUCCESS"
 export const UPDATE_RESIDENCIA_ERROR = "UPDATE_RESIDENCIA_ERROR"
 export const DELETE_RESIDENCIA = "DELETE_RESIDENCIA"
 export const DELETE_RESIDENCIA_SUCCESS = "DELETE_RESIDENCIA_SUCCESS"
 export const DELETE_RESIDENCIA_ERROR = "DELETE_RESIDENCIA_ERROR"
 export const CLEAN_RESIDENCIA = "CLEAN_RESIDENCIA"

 export const RESIDENCIA_ZONA = 'RESIDENCIA_ZONA'
 export const RESIDENCIA_ZONA_SUCCESS = 'RESIDENCIA_ZONA_SUCCESS'
 export const RESIDENCIA_ZONA_ERROR = 'RESIDENCIA_ZONA_ERROR'


 export const CREATE_AGENDA = "CREATE_AGENDA"
 export const CREATE_AGENDA_SUCCESS = "CREATE_AGENDA_SUCCESS"
 export const CREATE_AGENDA_ERROR = "CREATE_AGENDA_ERROR"
 export const VIEW_AGENDA = "VIEW_AGENDA"
 export const VIEW_AGENDA_SUCCESS = "VIEW_AGENDA_SUCCESS"
 export const VIEW_AGENDA_ERROR = "VIEW_AGENDA_ERROR"
 export const EDIT_AGENDA = "EDIT_AGENDA"
 export const EDIT_AGENDA_SUCCESS = "EDIT_AGENDA_SUCCESS"
 export const EDIT_AGENDA_ERROR = "EDIT_AGENDA_ERROR"
 export const UPDATE_AGENDA = "UPDATE_AGENDA"
 export const UPDATE_AGENDA_SUCCESS = "UPDATE_AGENDA_SUCCESS"
 export const UPDATE_AGENDA_ERROR = "UPDATE_AGENDA_ERROR"
 export const DELETE_AGENDA = "DELETE_AGENDA"
 export const DELETE_AGENDA_SUCCESS = "DELETE_AGENDA_SUCCESS"
 export const DELETE_AGENDA_ERROR = "DELETE_AGENDA_ERROR"
 export const CLEAN_AGENDA = "CLEAN_AGENDA"

 export const CREATE_DESARROLLO = "CREATE_DESARROLLO"
 export const CREATE_DESARROLLO_SUCCESS = "CREATE_DESARROLLO_SUCCESS"
 export const CREATE_DESARROLLO_ERROR = "CREATE_DESARROLLO_ERROR"
 export const VIEW_DESARROLLO = "VIEW_DESARROLLO"
 export const VIEW_DESARROLLO_SUCCESS = "VIEW_DESARROLLO_SUCCESS"
 export const VIEW_DESARROLLO_ERROR = "VIEW_DESARROLLO_ERROR"
 export const EDIT_DESARROLLO = "EDIT_DESARROLLO"
 export const EDIT_DESARROLLO_SUCCESS = "EDIT_DESARROLLO_SUCCESS"
 export const EDIT_DESARROLLO_ERROR = "EDIT_DESARROLLO_ERROR"
 export const UPDATE_DESARROLLO = "UPDATE_DESARROLLO"
 export const UPDATE_DESARROLLO_SUCCESS = "UPDATE_DESARROLLO_SUCCESS"
 export const UPDATE_DESARROLLO_ERROR = "UPDATE_DESARROLLO_ERROR"
 export const DELETE_DESARROLLO = "DELETE_DESARROLLO"
 export const DELETE_DESARROLLO_SUCCESS = "DELETE_DESARROLLO_SUCCESS"
 export const DELETE_DESARROLLO_ERROR = "DELETE_DESARROLLO_ERROR"
 export const CLEAN_DESARROLLO = "CLEAN_DESARROLLO"

 export const CREATE_PROTOTIPO = "CREATE_PROTOTIPO"
 export const CREATE_PROTOTIPO_SUCCESS = "CREATE_PROTOTIPO_SUCCESS"
 export const CREATE_PROTOTIPO_ERROR = "CREATE_PROTOTIPO_ERROR"
 export const VIEW_PROTOTIPO = "VIEW_PROTOTIPO"
 export const VIEW_PROTOTIPO_SUCCESS = "VIEW_PROTOTIPO_SUCCESS"
 export const VIEW_PROTOTIPO_ERROR = "VIEW_PROTOTIPO_ERROR"
 export const EDIT_PROTOTIPO = "EDIT_PROTOTIPO"
 export const EDIT_PROTOTIPO_SUCCESS = "EDIT_PROTOTIPO_SUCCESS"
 export const EDIT_PROTOTIPO_ERROR = "EDIT_PROTOTIPO_ERROR"
 export const UPDATE_PROTOTIPO = "UPDATE_PROTOTIPO"
 export const UPDATE_PROTOTIPO_SUCCESS = "UPDATE_PROTOTIPO_SUCCESS"
 export const UPDATE_PROTOTIPO_ERROR = "UPDATE_PROTOTIPO_ERROR"
 export const DELETE_PROTOTIPO = "DELETE_PROTOTIPO"
 export const DELETE_PROTOTIPO_SUCCESS = "DELETE_PROTOTIPO_SUCCESS"
 export const DELETE_PROTOTIPO_ERROR = "DELETE_PROTOTIPO_ERROR"
 export const CLEAN_PROTOTIPO = "CLEAN_PROTOTIPO"


 export const CREATE_ETAPA = "CREATE_ETAPA"
 export const CREATE_ETAPA_SUCCESS = "CREATE_ETAPA_SUCCESS"
 export const CREATE_ETAPA_ERROR = "CREATE_ETAPA_ERROR"
 export const VIEW_ETAPA = "VIEW_ETAPA"
 export const VIEW_ETAPA_SUCCESS = "VIEW_ETAPA_SUCCESS"
 export const VIEW_ETAPA_ERROR = "VIEW_ETAPA_ERROR"
 export const EDIT_ETAPA = "EDIT_ETAPA"
 export const EDIT_ETAPA_SUCCESS = "EDIT_ETAPA_SUCCESS"
 export const EDIT_ETAPA_ERROR = "EDIT_ETAPA_ERROR"
 export const UPDATE_ETAPA = "UPDATE_ETAPA"
 export const UPDATE_ETAPA_SUCCESS = "UPDATE_ETAPA_SUCCESS"
 export const UPDATE_ETAPA_ERROR = "UPDATE_ETAPA_ERROR"
 export const DELETE_ETAPA = "DELETE_ETAPA"
 export const DELETE_ETAPA_SUCCESS = "DELETE_ETAPA_SUCCESS"
 export const DELETE_ETAPA_ERROR = "DELETE_ETAPA_ERROR"
 export const CLEAN_ETAPA = "CLEAN_ETAPA"
 export const UPGRADE_ETAPA = "UPGRADE_ETAPA"
 export const UPGRADE_ETAPA_SUCCESS = "UPGRADE_ETAPA_SUCCESS"
 export const UPGRADE_ETAPA_ERROR = "UPGRADE_ETAPA_ERROR"



 export const SET_RELACION_PROTOTIPO_SUCCESS = "SET_RELACION_PROTOTIPO_SUCCESS"
 export const SET_RELACION_PROTOTIPO_ERROR = "SET_RELACION_PROTOTIPO_ERROR"
 export const SET_RELACION_PROTOTIPO = "SET_RELACION_PROTOTIPO"

 
 export const SET_RELACION_ETAPA_SUCCESS = "SET_RELACION_ETAPA_SUCCESS"
 export const SET_RELACION_ETAPA_ERROR = "SET_RELACION_ETAPA_ERROR"
 export const SET_RELACION_ETAPA = "SET_RELACION_ETAPA"