/// LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const GET_USER = 'GET_USER'
export const LOG_OUT = 'LOG_OUT'

/// ALERTS

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'


// Listado

 export const CREATE_LISTADO = "CREATE_LISTADO"
 export const CREATE_LISTADO_SUCCESS = "CREATE_LISTADO_SUCCESS"
 export const CREATE_LISTADO_ERROR = "CREATE_LISTADO_ERROR"
 export const VIEW_LISTADO = "VIEW_LISTADO"
 export const VIEW_LISTADO_SUCCESS = "VIEW_LISTADO_SUCCESS"
 export const VIEW_LISTADO_ERROR = "VIEW_LISTADO_ERROR"
 export const EDIT_LISTADO = "EDIT_LISTADO"
 export const EDIT_LISTADO_SUCCESS = "EDIT_LISTADO_SUCCESS"
 export const EDIT_LISTADO_ERROR = "EDIT_LISTADO_ERROR"
 export const UPDATE_LISTADO = "UPDATE_LISTADO"
 export const UPDATE_LISTADO_SUCCESS = "UPDATE_LISTADO_SUCCESS"
 export const UPDATE_LISTADO_ERROR = "UPDATE_LISTADO_ERROR"
 export const DELETE_LISTADO = "DELETE_LISTADO"
 export const DELETE_LISTADO_SUCCESS = "DELETE_LISTADO_SUCCESS"
 export const DELETE_LISTADO_ERROR = "DELETE_LISTADO_ERROR"


 export const CREATE_SECCION = "CREATE_SECCION"
 export const CREATE_SECCION_SUCCESS = "CREATE_SECCION_SUCCESS"
 export const CREATE_SECCION_ERROR = "CREATE_SECCION_ERROR"
 export const VIEW_SECCION = "VIEW_SECCION"
 export const VIEW_SECCION_SUCCESS = "VIEW_SECCION_SUCCESS"
 export const VIEW_SECCION_ERROR = "VIEW_SECCION_ERROR"
 export const EDIT_SECCION = "EDIT_SECCION"
 export const EDIT_SECCION_SUCCESS = "EDIT_SECCION_SUCCESS"
 export const EDIT_SECCION_ERROR = "EDIT_SECCION_ERROR"
 export const UPDATE_SECCION = "UPDATE_SECCION"
 export const UPDATE_SECCION_SUCCESS = "UPDATE_SECCION_SUCCESS"
 export const UPDATE_SECCION_ERROR = "UPDATE_SECCION_ERROR"
 export const DELETE_SECCION = "DELETE_SECCION"
 export const DELETE_SECCION_SUCCESS = "DELETE_SECCION_SUCCESS"
 export const DELETE_SECCION_ERROR = "DELETE_SECCION_ERROR"
