/// LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const GET_USER = 'GET_USER'
export const LOG_OUT = 'LOG_OUT'

/// ALERTS

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'


// Listado

 export const CREATE_LISTADO = "CREATE_LISTADO"
 export const CREATE_LISTADO_SUCCESS = "CREATE_LISTADO_SUCCESS"
 export const CREATE_LISTADO_ERROR = "CREATE_LISTADO_ERROR"
 export const VIEW_LISTADO = "VIEW_LISTADO"
 export const VIEW_LISTADO_SUCCESS = "VIEW_LISTADO_SUCCESS"
 export const VIEW_LISTADO_ERROR = "VIEW_LISTADO_ERROR"
 export const EDIT_LISTADO = "EDIT_LISTADO"
 export const EDIT_LISTADO_SUCCESS = "EDIT_LISTADO_SUCCESS"
 export const EDIT_LISTADO_ERROR = "EDIT_LISTADO_ERROR"
 export const UPDATE_LISTADO = "UPDATE_LISTADO"
 export const UPDATE_LISTADO_SUCCESS = "UPDATE_LISTADO_SUCCESS"
 export const UPDATE_LISTADO_ERROR = "UPDATE_LISTADO_ERROR"
 export const DELETE_LISTADO = "DELETE_LISTADO"
 export const DELETE_LISTADO_SUCCESS = "DELETE_LISTADO_SUCCESS"
 export const DELETE_LISTADO_ERROR = "DELETE_LISTADO_ERROR"
 export const CLEAN_LISTADO = "CLEAN_LISTADO"


 export const CREATE_SECCION = "CREATE_SECCION"
 export const CREATE_SECCION_SUCCESS = "CREATE_SECCION_SUCCESS"
 export const CREATE_SECCION_ERROR = "CREATE_SECCION_ERROR"
 export const VIEW_SECCION = "VIEW_SECCION"
 export const VIEW_SECCION_SUCCESS = "VIEW_SECCION_SUCCESS"
 export const VIEW_SECCION_ERROR = "VIEW_SECCION_ERROR"
 export const EDIT_SECCION = "EDIT_SECCION"
 export const EDIT_SECCION_SUCCESS = "EDIT_SECCION_SUCCESS"
 export const EDIT_SECCION_ERROR = "EDIT_SECCION_ERROR"
 export const UPDATE_SECCION = "UPDATE_SECCION"
 export const UPDATE_SECCION_SUCCESS = "UPDATE_SECCION_SUCCESS"
 export const UPDATE_SECCION_ERROR = "UPDATE_SECCION_ERROR"
 export const DELETE_SECCION = "DELETE_SECCION"
 export const DELETE_SECCION_SUCCESS = "DELETE_SECCION_SUCCESS"
 export const DELETE_SECCION_ERROR = "DELETE_SECCION_ERROR"
 export const CLEAN_SECCION = "CLEAN_SECCION"

 export const CREATE_USUARIO = "CREATE_USUARIO"
 export const CREATE_USUARIO_SUCCESS = "CREATE_USUARIO_SUCCESS"
 export const CREATE_USUARIO_ERROR = "CREATE_USUARIO_ERROR"
 export const VIEW_USUARIO = "VIEW_USUARIO"
 export const VIEW_USUARIO_SUCCESS = "VIEW_USUARIO_SUCCESS"
 export const VIEW_USUARIO_ERROR = "VIEW_USUARIO_ERROR"
 export const EDIT_USUARIO = "EDIT_USUARIO"
 export const EDIT_USUARIO_SUCCESS = "EDIT_USUARIO_SUCCESS"
 export const EDIT_USUARIO_ERROR = "EDIT_USUARIO_ERROR"
 export const UPDATE_USUARIO = "UPDATE_USUARIO"
 export const UPDATE_USUARIO_SUCCESS = "UPDATE_USUARIO_SUCCESS"
 export const UPDATE_USUARIO_ERROR = "UPDATE_USUARIO_ERROR"
 export const DELETE_USUARIO = "DELETE_USUARIO"
 export const DELETE_USUARIO_SUCCESS = "DELETE_USUARIO_SUCCESS"
 export const DELETE_USUARIO_ERROR = "DELETE_USUARIO_ERROR"
 export const CLEAN_USUARIO = "CLEAN_USUARIO"
 
 
 export const REDIRECT = "REDIRECT"

 export const VIEW_DEPARTAMENTO = "VIEW_DEPARTAMENTO"
 export const VIEW_DEPARTAMENTO_SUCCESS = "VIEW_DEPARTAMENTO_SUCCESS"
 export const VIEW_DEPARTAMENTO_ERROR = "VIEW_DEPARTAMENTO_ERROR"
 export const EDIT_DEPARTAMENTO = "EDIT_DEPARTAMENTO"
 export const EDIT_DEPARTAMENTO_SUCCESS = "EDIT_DEPARTAMENTO_SUCCESS"
 export const EDIT_DEPARTAMENTO_ERROR = "EDIT_DEPARTAMENTO_ERROR"
 export const UPDATE_DEPARTAMENTO = "UPDATE_DEPARTAMENTO"
 export const UPDATE_DEPARTAMENTO_SUCCESS = "UPDATE_DEPARTAMENTO_SUCCESS"
 export const UPDATE_DEPARTAMENTO_ERROR = "UPDATE_DEPARTAMENTO_ERROR"
 export const DELETE_DEPARTAMENTO = "DELETE_DEPARTAMENTO"
 export const DELETE_DEPARTAMENTO_SUCCESS = "DELETE_DEPARTAMENTO_SUCCESS"
 export const DELETE_DEPARTAMENTO_ERROR = "DELETE_DEPARTAMENTO_ERROR"
 export const CLEAN_DEPARTAMENTO = "CLEAN_DEPARTAMENTO"

 export const DEPARTAMENTO_SECCION = 'DEPARTAMENTO_SECCION'
 export const DEPARTAMENTO_SECCION_SUCCESS = 'DEPARTAMENTO_SECCION_SUCCESS'
 export const DEPARTAMENTO_SECCION_ERROR = 'DEPARTAMENTO_SECCION_ERROR'


 export const CREATE_AGENDA = "CREATE_AGENDA"
 export const CREATE_AGENDA_SUCCESS = "CREATE_AGENDA_SUCCESS"
 export const CREATE_AGENDA_ERROR = "CREATE_AGENDA_ERROR"
 export const VIEW_AGENDA = "VIEW_AGENDA"
 export const VIEW_AGENDA_SUCCESS = "VIEW_AGENDA_SUCCESS"
 export const VIEW_AGENDA_ERROR = "VIEW_AGENDA_ERROR"
 export const EDIT_AGENDA = "EDIT_AGENDA"
 export const EDIT_AGENDA_SUCCESS = "EDIT_AGENDA_SUCCESS"
 export const EDIT_AGENDA_ERROR = "EDIT_AGENDA_ERROR"
 export const UPDATE_AGENDA = "UPDATE_AGENDA"
 export const UPDATE_AGENDA_SUCCESS = "UPDATE_AGENDA_SUCCESS"
 export const UPDATE_AGENDA_ERROR = "UPDATE_AGENDA_ERROR"
 export const DELETE_AGENDA = "DELETE_AGENDA"
 export const DELETE_AGENDA_SUCCESS = "DELETE_AGENDA_SUCCESS"
 export const DELETE_AGENDA_ERROR = "DELETE_AGENDA_ERROR"
 export const CLEAN_AGENDA = "CLEAN_AGENDA"